services:
    truthseeker:
        image: grizzlar99/eliza-agent:latest
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        environment:
            - OPENAI_API_KEY=$OPENAI_API_KEY
            - TAVILY_API_KEY=$TAVILY_API_KEY
            - EXA_API_KEY=$EXA_API_KEY
            - SERPER_API_KEY=$SERPER_API_KEY
            - TEE_MODE=DOCKER
        ports:
            - "3000:3000"
        restart: always
