[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
viaIR = true
evm_version = "paris"
ffi = true
